apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-configmap
data:
  db_name: postgresdb
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
data:
  db_user: YWRtaW5kYg==
  db_password: YWRtaW5wYXNzd29yZA==